from quantizations.LSQ import LSQQuantStrategy
from quantizations.APoT import APoTQuantStrategy
from quantizations.QDrop import QDropQuantStrategy
from quantizations.AdaRound import AdaRoundQuantStrategy
